language: java
jdk:
- oraclejdk8
cache:
  directories:
  - .autoconf
  - $HOME/.m2
install:
- wget -O BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
- git config --global --unset core.autocrlf
- java -jar BuildTools.jar --rev 1.11
script: mvn clean package

addons:
  artifacts: true